// <auto-generated />

using Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Energomera.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20220412125824_AddItems")]
    partial class AddItems
    {
        protected void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.16");

            modelBuilder.Entity("Energomera.Entitys.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "feugiat in"
                        },
                        new
                        {
                            Id = 2,
                            Name = "nec tincidunt"
                        },
                        new
                        {
                            Id = 3,
                            Name = "cursus vitae"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
